/* Developed by Juno_okyo – J2TEAM */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var a=0;return function(c){return $jscomp.SYMBOL_PREFIX+(c||"")+a++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var c=0;return $jscomp.iteratorPrototype(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
(function(){function a(a,k){return new Promise(function(b){fetch("https://graph.facebook.com/"+encodeURIComponent(d(a))+"?fields=id&access_token="+k).then(function(a){return a.json()}).then(function(a){a.id&&b(a.id)})})}function c(){return new Promise(function(a){var b=new FormData;b.append("app_id",0x96e458393762);b.append("redirect_uri","fbconnect://success");b.append("display","popup");b.append("return_format","access_token");b.append("fb_dtsg",g());b.append("sso_device","ios");fetch("https://"+
window.top.location.hostname+"/v2.9/dialog/oauth/confirm",{method:"POST",credentials:"same-origin",body:b}).then(function(a){return a.text()}).then(function(b){a(b.match(/access_token=([^&]+)/)[1])})})}function d(a){try{var b=new URL(a),e=b.pathname.substr(1),c="profile.php"===e?b.searchParams.get("id"):e;return c.includes("/")?!1:c}catch(l){return console.error(l.message),!1}}function m(a){if("object"!==("undefined"===typeof a?"undefined":n(a)))if("string"===typeof a)try{a=JSON.parse(a)}catch(e){return!1}else return!1;
var b=new FormData;Object.keys(a).map(function(c){b.append(c,a[c])});return b}function h(){if("function"!==typeof require)return null;try{return require("CurrentUserInitialData").USER_ID||document.cookie.match(/c_user=([0-9]+)/)[1]}catch(b){return null}}function g(){if("function"!==typeof require)return null;try{return require("DTSGInitialData").token||document.querySelector('[name="fb_dtsg"]').value}catch(b){return null}}$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbolIterator();var n=
"function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){$jscomp.initSymbol();$jscomp.initSymbol();$jscomp.initSymbol();return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},f=prompt("Enter Facebook URL:");f&&0<f.length&&c().then(function(b){a(f,b).then(function(a){var b=/\/permalink\/([0-9]+)/.exec(window.top.location.href);null!==b&&(a={ft_ent_identifier:b[1],comment_text:"@["+a+":0] b\u00e0i tr\u00f9ng nh\u00e9!",
av:h(),__user:h(),__a:1,fb_dtsg:g(),source:2,client_id:"1489983090155:3363757627",session_id:"84d81e4"},fetch("https://www.facebook.com/ufi/add/comment/?dpr=1",{method:"POST",credentials:"include",body:m(a)}))})})})();

